[package]
name = "go-pion-webrtc"
version = "0.0.1"
edition = "2021"

[dependencies]
libc = "0.2.126"
libloading = "0.7.3"
once_cell = "1.12.0"
ouroboros = "0.15.0"
tempfile = "3.3.0"

[build-dependencies]
bindgen = "0.60.1"
